### ISSUE TITLE
Feature request: Ability to add annotations via the YouTube API.

### ISSUE THREAD

**Issue by stephenwithav** [google/google-api-go-client#104]
Having the ability to add annotations via the YouTube API would be fantastic.

Something like:

```go
	upload := &youtube.Video{
		Snippet: &youtube.VideoSnippet{
			Title:       "Test Title",
			Description: "Test Description", // can not use non-alpha-numeric characters
			CategoryId:  "22",
		},
		Status: &youtube.VideoStatus{PrivacyStatus: "private"},
		Annotations: &youtube.VideoAnnotations{
			{
				Type: "SpeechBubble",
				StartTime: 1.21,
				EndTime: 88.6,
				Text: "1.21 Gigawatts!",
				Font: "Arial",
				Color: "White",
				Background: "#f00",
			},
			{
				Type: "Note",
				StartTime: 25.0,
				EndTime: 30.0,
				Text: "Check out this merchandise!",
				Link: {
					Type: "Merch",
					URL: "http://merchant.partner/uri",
				},
			},
		},
	}
```

**Comment by gmlewis** [comment]
We can only do what the API supports.
If you can figure out how to do this with the YouTube API:
https://developers.google.com/youtube/v3/
and are able to perform a working test with the API Explorer:
https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.videos.insert
then please let me know if you can not do the same thing with the google-api-go-client and I will see what I can do to get it working.
Otherwise, we will need to contact the YouTube API team and ask them to support what you would like.

So please play around with that and let me know.  Meanwhile, I'll see if I can find the owners of the YouTube API and discuss this with them.

**Comment by stephenwithav** [comment]
Thank you, @gmlewis.

It's not possible with the YouTube API, unfortunately.  (Only [invideoPromotion](http://youtube-eng.blogspot.com/2013/10/spice-up-your-channel-with-invideo_2.html) is.)

The annotations API appears to be simple enough and well-designed, based on watching the network requests.  Would I be penalized if I created (and used) a hack to add annotations along with the videos I upload using the YouTube API?

**Comment by gmlewis** [comment]
Hmmm... I'm not that familiar with the YouTube or Annotation APIs to know the answer to your question...
But speaking for myself only (not Google), it seems to me that if you can figure out how to add annotations to your video uploads that you should try it out and see if you can get it to work.  I personally don't see the harm in that.

I'll close this issue, but if you have updates from your experiments, feel free to post them here so others can find them easily.

**Comment by stephenwithav** [comment]
Thanks again.  I'll give it a shot. :)

Would updates include non-API solutions?

**Comment by gmlewis** [comment]
I would certainly like to see solutions, and it doesn't hurt to add comments here if you want to... we may not be able to incorporate them into this auto-generated library, but I think others may also appreciate seeing your solutions.
