### ISSUE TITLE
Gmail API does not accept multiple labelIds parameters

### ISSUE THREAD

**Issue by ConradIrwin** [google/google-api-go-client#105]
At the moment you cannot pass multiple `labelIds` parameters to the gmail endpoint using the builder API:

I tried to do this:

    gmailService.Users.Threads.List("me").LabelIds("INBOX").LabelIds("CATEGORY_PERSONAL")

But the second call to `labelIds` overwrites the first one, and so it makes a request to:

    https://content.googleapis.com/gmail/v1/users/me/threads?labelIds=CATEGORY_PERSONAL

instead of:

    https://content.googleapis.com/gmail/v1/users/me/threads?labelIds=CATEGORY_PERSONAL&labelIds=INBOX

**Comment by ConradIrwin** [comment]
Thanks @gmlewis

**Comment by gmlewis** [comment]
You're welcome!  Please let me know if you have any problems with it.
Many thanks to @mcgreevy who made a lot of improvements during the code review process!

**Comment by gmlewis** [comment]
This change broke the storage API, so I reverted.  See Issue #110.
Re-opening to investigate and add unit test that demonstrates breakage and fixes the problem.

**Comment by gmlewis** [comment]
Michael and I have a CL that we believe fixes this issue
(located here: https://code-review.googlesource.com/#/c/3610 )
but would like to get integration tests incorporated into the project before submitting this so that we don't have another breakage of a major API.
Feel free to patch in the CL and try it out if you would like repeated parameters.
