### ISSUE TITLE
Resumable upload loops infinitely when the resource to update is not writable

### ISSUE THREAD

**Issue by clementdenis** [google/google-api-go-client#128]
This can happen for example when trying to upload a new version of a Drive file that is only readable by the caller.

Fix available here: https://code-review.googlesource.com/4080

**Comment by clementdenis** [comment]
@mcgreevy Any update on this? I see you worked on the resumable upload loop in the last days, but the infinite loop still happens when updating read-only resources. My fix can still be merge with master.

**Comment by mcgreevy** [comment]
Hi @clementdenis, I was waiting for your patch, and didn't see it because github does not send me notifications on edits to comments (it seems that you posted the link to your patch by modifying your original comment).

I also didn't get a notification on the codereview from gerrit, because I wasn't listed as a reviewer.

I'm adding myself and taking a look now.

**Comment by clementdenis** [comment]
@mcgreevy  The changes are up, you should have been notified this time.

Sorry about the multiple notifications, I'm still getting used to the process.
