### ISSUE TITLE
Did something change with endpoints configuration?

### ISSUE THREAD

**Issue by zboralski** [google/google-api-go-client#131]
It seems really hard to get an updated discovery...

I have made changes to my endpoints... deployed to app engine... No errors but I can't get the generator to see the discovery definition doesn't update at all.

**Comment by gmlewis** [comment]
Can you please be more specific what the problem is that you are seeing?
Can you give before/after examples?
Which APIs are you using?
Does this involve https://www.googleapis.com/discovery/v1/apis ?
Why are you running the generator on App Engine (as opposed to using the already-generated APIs on App Engine)?

**Comment by mcgreevy** [comment]
61d74df might be relevant.

**Comment by zboralski** [comment]
@gmlewis, the generator seemed to have problem getting updated endpoints configuration. It seemed the issue was caused by the long version names containing github commit hashes that we were using that cause Google's hostname routing to lag or choke.

We are using the generator to create our endpoint clients for our own endpoints that are deployed on App Engine.
