### ISSUE TITLE
Provide a way to easily retry transient errors

### ISSUE THREAD

**Issue by evanj** [google/google-api-go-client#142]
Many of the Google APIs occasionally fail with errors that can be safely retried. `gensupport.Retry` already encodes some reasonable logic for determining which errors are safe to retry, and a reasonable backoff policy. Would it make sense to expose it in some "friendlier" way? Would it makes sense to do something like a per-call option, passed into Do()?

Currently I'm using a hack of adding it to a RoundTripper for my HTTP client, although I'm a bit concerned that this blanket policy may actually be too aggressive, and it may retry calls that  should not be.

**Comment by nightlyone** [comment]
Yes, that would be awesome. Esp. since some APIs (e.g. bigquery) are trolling the user with "helpful" messages like: `googleapi: Error 503: Error encountered during execution. Retrying may solve the problem., backendError`

**Comment by Dynom** [comment]
I'm struggling with this too, however I think we should have more flexibility in terms of injecting a more custom HTTP client instead of parameterising Do()

e.g. something like this would be flexible enough for my use-cases:
```go
func getGoogleTranslateService() (*translate.Service, error) {
	httpClient := &http.Client{
		Transport: &transport.APIKey{
			Key: os.Getenv("GOOGLE_API_KEY"),
		},
	}

	// Wrapping the http client and respect the http.Client interface
	pesterClient := pester.NewExtendedClient(httpClient)
	pesterClient.Backoff = pester.ExponentialBackoff
	pesterClient.MaxRetries = 50

	return translate.New(pesterClient)
}
```

This currently fails because `translate.New(client *http.Client)` without type assertion, which (I'm guessing) would solve the inflexibility?

**Comment by odeke-em** [comment]
Am wondering, could we change these signatures up so that the places that require a client `*http.Client` could instead take an HTTPClient interface? The HTTPClient interface could be declared as
```go
type HTTPClient interface {
    Do(req *http.Request) (res *http.Response, err error)
    Get(url string) (res *http.Response, err error)
    Post(urstring, bodyType string, body io.Reader) (res *http.Response, err error)
    PostForm(url string, values url.Values) (res *http.Response, err error)
    Head(url string) (res *http.Response, err error)
    // Add any other methods here if necessary
}
```

this I think will solve the problems described in this issue without breaking the code and in fact we could have an ssertion in the *gen.go files such as
```go
var _ HTTPClient = http.DefaultClient
```
to ensure that a raw *http.Client can always be accepted.

I encountered this problem previously and had to do a few nasty hacks to get retry to work without having to change the client https://github.com/odeke-em/drive/blob/v0.3.7/src/misc.go#L131-L177

**Comment by Dynom** [comment]
Hi @odeke-em. An interface would solve the problem, but afaik there isn't any available? In fact I'm about the post an issue to https://github.com/golang/go/issues to add it.

**Comment by jba** [comment]
Unfortunately, we can't change the concrete type to an interface without breaking a lot of code.

These clients are in maintenance mode. We don't plan to address this issue.

@pongad for the next generation of clients.
