### ISSUE TITLE
Your client does not have permission to get URL / from this server.

### ISSUE THREAD

**Issue by shahabsiavash** [google/google-api-go-client#155]
Hello,

I don't know it should be here o not. Please help me if it shouldn't be.I am from Iran. I'm a graphic and font designer.

We could use **Google Adsense, Adwords, Codes,**... But we always get errors like this:

**403**. That’s an error.
_Your client does not have permission to get URL / from this server. That’s all we know._

For years we have known that it's because of the **US sanctions**. There are a lot of websites (over 10 millions) that are blocked in Iran. At the other hand we suffer from the **"free world"** too. 

Why should websites be forbidden from USA while there is no danger in these services? What could be done with these services to harm US government? We heard that 2 years ago technology and internet sanctions were removed. Were not?

And it's not all of that! Recently I have been designing a website using an online service. **A third party.** And still I get this error!

I recently found out that this kind of error happens everywhere! Netherland, Russia,...
Can you please explain this?

[http://www.imxprs.com](http://www.imxprs.com)

**403**. That’s an error.
_Your client does not have permission to get URL / from this server. That’s all we know_

Is this universal? Why is this?

Is there any way that I can solve this? Otherwise the website can not be explored by no Iranian.

Thanks a lot.

**Comment by bradfitz** [comment]
Usually when sites are blocking Iran (that is, when it's not Iran blocking stuff itself), I believe it's because those sites are complying with U.S. laws around crypto export restrictions.

I do know that Google has lawyers who pay attention to all these rules, so when we can relax things, I imagine we will. We do not benefit from blocking users from using our services.

I am not a lawyer, though, and I don't work for the US State Department or Treasury, and I doubt you'd get any of those people on this bug explaining it further, so I'll regrettably close this without a more satisfying answer.

**Comment by mitra921** [comment]
سلام

**Comment by mitra921** [comment]
سلام

**Comment by mitra921** [comment]
س

**Comment by mitra921** [comment]
ل

**Comment by mitra921** [comment]
ا

**Comment by mitra921** [comment]
م

**Comment by mitra921** [comment]
_

**Comment by mitra921** [comment]
- [ ] 

1.

**Comment by mitra921** [comment]
Aa

**Comment by mitra921** [comment]
Hi

**Comment by mitra921** [comment]
His

**Comment by mitra921** [comment]
Y
