### ISSUE TITLE
Support resumable media upload

### ISSUE THREAD

**Issue by gmlewis** [google/google-api-go-client#17]
**agoode@google.com** on 12 Nov 2012 at 4:15:

```
The library only supports the "simple" upload protocol. It would be very good 
to support "resumable" so that large files can be reliably uploaded.

https://developers.google.com/discovery/v1/using#discovery-doc-methods-mediauplo
ad
```

**Comment by gmlewis** [comment]
**gmlewis@google.com** on 26 Apr 2014 at 10:40:

_Status changed to **Accepted**._

**Comment by gmlewis** [comment]
Successfully auto-migrated from code.google.com:
https://code.google.com/p/google-api-go-client/issues/detail?id=17

**Comment by gmlewis** [comment]
ResumableMedia support was added by:
https://github.com/google/google-api-go-client/commit/8ec38e5b9349a4031f50fbf37f9c10542eed18de

Although this feature is currently fully functional and supports large file uploads, the API will likely be undergoing some changes due to review feedback (to simplify the dev experience), so I'm leaving this issue open.

**Comment by dragomit** [comment]
Commenting here in lieu of creating new issue.

In the current resumable upload implementation, upload will be resumed under limited circumstances - typically only when server returns 5xx HTTP status code. Transient transport layer errors are currently not handled, and will instead cause upload to fail.

A more robust implementation should try to differentiate between permanent lower layer errors such as reader error, and transient lower layer errors such as connection error, TCP timeout, etc. Permanent errors would cause the upload to fail immediately, while transient errors would trigger upload resumption, after exponential backoff.

I've also observed an opposite scenario where the library tries indefinitely to resume upload even though a permanent errors has occured. This can happen if the server for some reason marks the upload as failed, after which all subsequent requests for that upload will receive HTTP 400 response. Current implementation does not distinguish between 5xx and 400, and will instead react to any response status code other than 308 and 200 by starting another upload resumption cycle. I believe any 4xx response code should be treated as permanent error.

**Comment by gmlewis** [comment]
This will still be true after the incorporation of https://code-review.googlesource.com/#/c/2762/
correct?

**Comment by dragomit** [comment]
Correct, https://code-review.googlesource.com/#/c/2762/ will add support for the case when media size is not known up-front, but will not change how various errors are handled.

**Comment by porjo** [comment]
What is the current state of resumable uploads in 2017?

**Comment by gmlewis** [comment]
@mcgreevy may be able to comment on the current state of resumable uploads.

**Comment by porjo** [comment]
[My app](https://github.com/porjo/youtubeuploader) has been getting a lot of cancelled uploads lately due to `Error 503:  Backend Error`. I'd be great to be able to resume the upload if possible, but I'm not seeing an obvious way to do that currently.

**Comment by mcgreevy** [comment]
We already use resumable uploads and automatically retry chunks if the chunk size is non-zero and the Reader has content which is longer than this chunk size.

So, if you are seeing 503s, that means that it is the initial request (which initiates the upload) that is failing.  The code that currently performs this initial request is written to work with both resumable and non-resumable uploads.  In the case of non-resumable uploads, it is not safe to retry the request, because  some of the data to be uploaded will already have been read from the Reader.  Retrying the request would drop that data.

@jba we should at the least treat the resumable and non-resumable cases differently here: there's no reason that we can't retry the initial upload request when we're doing resumable uploads. Better than this would be to use resumable uploads always, but this would mean buffering some data in situations where we're not currently doing so, which might blow up memory requirements depending on how people are using the library. I am stretched from time right now, but will try to add some more detail to this comment next week.

**Comment by jba** [comment]
This was implemented for the storage client at https://github.com/GoogleCloudPlatform/google-cloud-go/commit/8fa5f76869d7146b0f2d1ecb790b18932e5923ae. 

Closing this issue because none of the other clients in this repo seem to need this, and these clients are in maintenance mode.
