### ISSUE TITLE
Unable to do anything with response Any protos in REST client

### ISSUE THREAD

**Issue by melissachang** [google/google-api-go-client#177]
In Go REST Apiary libraries, response Any proto is map[string]interface{}. I can't figure out how to convert this to any other type:
- byte[]
- Any proto
- Original proto that Any proto represents

Ross requested me to mention some people: @bradfitz @jba @zombiezen

**Comment by zombiezen** [comment]
The concrete proposal I had was that instead of having these fields generate an `interface{}` type, they should store a `json.RawMessage`.  Then the user of the client could pick which message it should be and it becomes regular JSON semantics.

This would be a breaking API change, but I would argue that `map[string]interface{}` is unhelpful enough that it's worth it.  FWIW, the current generator renamed the actual `OperationMetadata` struct to `OperationMetadata1` to avoid conflicts with the `type OperationMetadata interface{}`.

**Comment by zombiezen** [comment]
So in testing this out in the real world, golang/go#14493 actually has a correctness issue: `json.RawMessage` fields get encoded as base64.  While the correct behavior will land in Go 1.8, we have too many targets (namely App Engine) that aren't updated to 1.8.  As I see it, there are two options:

1. Roll back b679263.
2. Roll forward and use `*json.RawMessage`.

@jba, thoughts?

**Comment by zombiezen** [comment]
@jba suggested an even better solution: creating a `googleapi.RawMessage` type that has the correct behavior, independent of Go version.

**Comment by dsnet** [comment]
Copying the [implementation of `json.RawMessage`](https://github.com/golang/go/blob/9073af247d602dff4633710adf90c8b3c1869c45/src/encoding/json/stream.go#L244-L264) sounds like a good way to get around this problem. I think using `*json.RawMessage` is really dirty.

It would be nice to be able to alias `googleapi.RawMessage` as `json.RawMessage` in the not-so-distant future.

**Comment by zombiezen** [comment]
Yup, https://code-review.googlesource.com/9811 out for review does exactly this.
