### ISSUE TITLE
Mention googleapi subpackage more prominently in docs

### ISSUE THREAD

**Issue by zombiezen** [google/google-api-go-client#182]
`google.golang.org/api/googleapi` has a number of useful functions that help with other APIs in this repo.  Now that the list of APIs is so long, we need to call it out in the docs as part of basic usage.

**Comment by bradfitz** [comment]
Before you do so, somebody should do a pass over googleapi and make it not embarassing.

Because it also was the "gensupport" package for a long time, before "gensupport" was created, it still is a little gross.

To pick one example: https://godoc.org/google.golang.org/api/googleapi#CombineFields

> // CombineFields combines fields into a single string.

How? Why?

And is https://godoc.org/google.golang.org/api/googleapi#ContentTyper deprecated? I thought so.

Actually, the package isn't as bad as I remember. The move to gensupport cleaned it up a fair bit.

**Comment by mcgreevy** [comment]
@bradfitz 's sentiment is captured in issue #113 , which I filed a short time after I introduced the gensupport package (then called "internal"). I don't think that we ever did much of the cleanup migration -- the introduction of gensupport just gave us a home to put new non-user-facing stuff, so the bloat of implementation details in googleapi stopped getting worse.

**Comment by jba** [comment]
This repo is in maintenance mode. We don't plan on making cosmetic changes like this.
