### ISSUE TITLE
Panic when generating serviceuser:v1

### ISSUE THREAD

**Issue by saicheems** [google/google-api-go-client#188]
```
2017/02/10 12:41:21 Generating API serviceuser:v1
panic: Clash on name Service
```

See `google-api-go-generator/gen.go:1050`.

Seems there's a public field also named Service...

**Comment by jba** [comment]
@zombiezen, as you'll see, this panic is explicit in the code, not the result of some bug. I'm not sure how to handle it.

**Comment by gmlewis** [comment]
Renaming the top-level `Service` is not an option, in my opinion, as it would potentially break all users of this library of APIs.

It might be possible to patch the `serviceuser:v1` API and rename their `Service` struct.

I'm leaning toward temporarily black-listing the `serviceuser:v1` API in order to update the other APIs.

**Comment by gmlewis** [comment]
Created https://code-review.googlesource.com/#/c/11171/ as recommended by @broady.

**Comment by broady** [comment]
Yes, sorry, missed this bug.

Renaming the struct is the correct thing to do.

**Comment by gmlewis** [comment]
Fixed in https://github.com/google/google-api-go-client/commit/64485db7e8c8be51e572801d06cdbcfadd3546c1
Thank you, @broady!
