### ISSUE TITLE
drive/v3 Files.Update can't remove properties or appProperties

### ISSUE THREAD

**Issue by srouquette** [google/google-api-go-client#201]
based on the comment of File.AppProperties:
// Entries with null values are cleared in update and copy requests.
AppProperties map[string]string `json:"appProperties,omitempty"`

Sadly AppProperties is a map of string, and a string can't be nil (but it can be empty).
There are other fields in File to manage empty fields, called ForceSendFields and NullFields, but they only work for the top level fields in File, and doesn't work recursively in Properties or AppProperties.

**Comment by catsby** [comment]
I think this is more widespread. For example, while debugging an issue in https://github.com/hashicorp/terraform, I noticed that once I enabled a feature, I could no longer disable it via the API. The feature is behind a boolean flag `StorageAutoResize`:

    StorageAutoResize bool `json:"storageAutoResize,omitempty"`

Because `false` qualifies as `empty` here, a false value to turn this feature off will be excluded from the API call. 

- https://github.com/google/google-api-go-client/blob/master/sqladmin/v1beta4/sqladmin-gen.go#L1950

**Comment by srouquette** [comment]
I tried both `ForceSendFields` and `NullFields` but this won't help me. It only works for File member fields, and I need to send `nil` in `AppProperties`. `ForceSendFields` and `NullFields` aren't recursive.

**Comment by jba** [comment]
@catsby, `ForceSendFields` should work for you. @srouquette, as you note, your problem is deeper. 

Maybe we should generate `map[string]interface{}` in this case. Then you could set a field to either a string or nil (or, unfortunately, to anything else).

There is no way to tell from the discovery doc that nulls are significant, so we'd need to note that separately (perhaps hardcode it into the generator).

/cc @zombiezen @adams-sarah @bradfitz @broady

**Comment by srouquette** [comment]
@jba that's what I did in [my fork](https://github.com/google/google-api-go-client/compare/master...srouquette:master).

I didn't create a pull request because it may break for those who are using AppProperties as a map of strings.

**Comment by jba** [comment]
@srouquette That code is generated, so unfortunately the full fix isn't that easy. Glad that you could fork and move on.

**Comment by catsby** [comment]
@jba `ForceSendFields` did indeed work for me, thanks 😄 

It's unfortunate that I need to use that though, both in terms of remembering and checking if it's needed, and maintaining this whitelist of fields that I need to make sure are set.

**Comment by jba** [comment]
@catsby I think `StorageAutoResize` is a candidate for pointer-ness. I'll make a CL.

**Comment by jba** [comment]
https://code-review.googlesource.com/13112.

**Comment by catsby** [comment]
Thanks @jba !

**Comment by jba** [comment]
CL submitted. 

@catsby After a `go get -u` of the sqladmin package, your code will break because `StorageAutoResize` is a `*bool`. Here's a [helper](https://godoc.org/google.golang.org/api/googleapi#Bool) for getting a pointer to a `bool`.

**Comment by catsby** [comment]
Thanks @jba !

**Comment by jba** [comment]
We need to handle map-valued fields where the map's values can sometimes be null. This happens whenever we generate a `map[string]string` for a resource, like the one mentioned in this thread or the `Labels` field of many resources. Typically it's the update or patch methods of the resource that allow you to set a key's value to null, to delete the key. Simply omitting the key from the map (at least for patch) does nothing to the corresponding key on the backend resource; you must explicitly supply the key with a JSON `null`.

While we could generate `map[string]interface{}` for these fields, that has two problems: first, it breaks many existing clients; second, it becomes annoying to retrieve values from the map (you need a cast most of the time).

We already have a `NullFields` field in each resource for handling this problem at the field level. `NullFields` is a slice of strings that refer to fields; when marshaling to JSON, the corresponding fields are set to `null` instead of being omitted or set to their default values. 

I propose we simply extend the semantics of `NullFields`. Strings that contain a dot, like 'F.K", cause the value of key "K" of the map-valued field `F` being marshaled as `null`. For example:
```go
File{AppProperties: map[string]string{"prop": ""}}
```
will marshal (now and in this proposal) as 
```json
{"appProperties": {"prop": ""}}
```
which will set `prop` to the empty string. But with my proposal, the user could write
```go
File{AppProperties: map[string]string{}, NullFields: []string{"AppProperties.prop"}}
```
which will marshal as
```json
{"appProperties": {"prop": null}}
```
As I've written it, map keys appearing in `NullFields` don't even have to be present in the given map value. We could also require that they be present (with an empty value) if desired.

Alternative syntax: we could use `"F[K]"` instead of `F.K`, to make it look more like map access and to clearly delimit `K` (in the event that `K` contains dots, for example).

This fix only requires modifying `gensupport.MarshalJSON`. Neither the generator nor any generated client needs to change.

@zombiezen Does this work for you? I'd like your approval before I start work.

**Comment by zombiezen** [comment]
@jba SGTM. I'd imagine that we only have this cost when there's a map, and we can probably extract out the difficult bits of the logic to a function.

I take it empty string can't be used to signify null in these cases?

**Comment by jba** [comment]
> I take it empty string can't be used to signify null in these cases?

It can't for labels, at least. An empty label value is legal.

**Comment by zombiezen** [comment]
SGTM

**Comment by jba** [comment]
@srouquette You should now be able to write
```
NullFields: []string{"AppProperties.foo"}
```
to delete the "foo" app property.

Please let me know if that doesn't work (or if it does!).

**Comment by jba** [comment]
Assuming fixed.

**Comment by srouquette** [comment]
@jba sorry, just saw your comment, I'll check it out. Thanks for the fix  :)

**Comment by srouquette** [comment]
@jba is your fix available on github? You mentioned 12 days ago it was fixed, but the latest commit on master was 19 days ago.

**Comment by jba** [comment]
I'll see why our mirroring isn't working. But it shouldn't matter if you use `go get -u`, because the actual repo is https://code.googlesource.com/google-api-go-client.

**Comment by srouquette** [comment]
ok, i'll update my url, I'm using glide to update the dependencies

**Comment by srouquette** [comment]
ok, it seems I now pull the latest code, your patch is in schemaToMap? I see useNullMaps in there.

It's still not working. I only specify NullFields = []string{"AppProperties.ufo.lock.owner", "AppProperties.ufo.lock.created", "AppProperties.ufo.lock.expires"}

Do I need to specify another field?
I check the result like this:

	if fileJson, e := json.Marshal(f); e == nil {
		log.Debug(string(fileJson))
	}

But appProperties isn't exported.

**Comment by srouquette** [comment]
@jba: ok, I found a workaround. Your fix works if I send properties with values and others in NullFields, it will create an appProperties with both. But if I send only NullFields, even if AppProperties is an empty map (not nil), it won't export anything.

I specified ForceSendFields: []string{"AppProperties"}, and it fixed my problem.

**Comment by jba** [comment]
Yes, that's actually how it's supposed to work. I agree it's a little confusing.

**Comment by srouquette** [comment]
ok, thanks a lot for your help  :)
