### ISSUE TITLE
internal: export internal.DialSettings from option package

### ISSUE THREAD

**Issue by rakyll** [google/google-api-go-client#211]
It is impossible for packages to provide their own option.ClientOption types without this type exported. External packages can benefit from being able to implement option.ClientOption to follow the client construction pattern in the style of without having to depend on the option package:

```
func NewClient(ctx context.Context, projectID string, opt option.ClientOption) (*Client, error)
```

/cc @jba

**Comment by jba** [comment]
So we're talking about
```
type ClientOption interface {
	Apply(*internal.DialSettings)
}
```
and you need to refer to `DialSettings` so you can implement this interface.

But `DialSettings` itself is useless to you, presumably, since it can already be fully manipulated by existing options. So I assume you would write a dummy `Apply`, then filter your option out of the list before passing the rest to one of the `transport` methods.

If that is right, then maybe a better design would be
```
type ClientOption interface {
	IsClientOption()
}

type clientOption interface {
	ClientOption
	Apply(*internal.DialSettings)
}
```

WDYT?
@broady you wanted this too, right?
/cc @zombiezen @adams-sarah

**Comment by rakyll** [comment]
@jba, that is right! I can equally benefit from:

```
type ClientOption interface {
	IsClientOption()
}
```

All I want to do is to be able to use the option.ClientOption variadic args for specific options exported from my custom package.

**Comment by jba** [comment]
This can be accomplished by embedding `option.ClientOption` .
