### ISSUE TITLE
Requesting files list with "domain" corpora fails for service account (400 Invalid value)

### ISSUE THREAD

**Issue by jacksongabbard** [google/google-api-go-client#218]
Using the following code, I'm requesting the files list from the Drive API via a service account. The service account has domain wide delegation and I've ensured that in the Admin console the service account ID is added and has all the scopes it might need.

```
config, configErr := google.JWTConfigFromJSON(
  credential,
  drive.DriveScope,
  drive.DriveReadonlyScope,
  drive.DriveAppdataScope,
  drive.DriveFileScope,
  drive.DriveMetadataScope,
  drive.DriveMetadataReadonlyScope,
  drive.DrivePhotosReadonlyScope,
)
if configErr != nil {
  log.Fatalf("Could not create a config: %v", configErr)
  return false
}

client := config.Client(ctx)
service, serviceErr := drive.New(client)
if serviceErr != nil {
  log.Fatalf("Unable to get a drive service instance: %v", serviceErr)
  return false
}

fileListCall := service.Files.List()
fileListCall = fileListCall.Corpora("domain")
fl, fileListErr := fileListCall.Do()
if fileListErr != nil {
  log.Fatalf("Unable to list files: %v", fileListErr)
  return false
}
```

The above fails consistently with the error: 
`2017/07/17 17:32:02 stderr: 2017/07/17 17:32:02 Unable to list files: googleapi: Error 400: Invalid Value, invalid`

If I change the Corpora to "user," it successfully shows me the files of the service user. If I make this API call from the API console using my own user account with OAuth2 enabled, the "domain" corpora also succeeds, which leads me to believe that there's something specific to service accounts making "domain" corpora calls that results in the 400.

**Comment by jacksongabbard** [comment]
For thoroughness, here is the Admin console UI showing the app setup with the correct/expected scopes

![screenshot 2017-07-17 18 47 08](https://user-images.githubusercontent.com/544550/28281878-70456db8-6b20-11e7-8e3b-4618fa60243f.png)

**Comment by jacksongabbard** [comment]
![](https://user-images.githubusercontent.com/544550/28387453-22cace04-6cc7-11e7-94cc-0b1ffebce336.gif)

**Comment by bradfitz** [comment]
Please no animated GIFs. Words will suffice.

**Comment by jacksongabbard** [comment]
Sure thing (though GIFs are much cuter -- you can't deny that). I was just giving this a nudge to see if someone might follow up.

**Comment by jba** [comment]
This is unlikely to be related to this client. I've contacted the drive team internally.

**Comment by jba** [comment]
Response from drive team:

It appears that the user is trying to make a request to Drive as the service account instead of by impersonating a user in the domain. Service accounts commonly do not belong to a domain even if they were created by a domain user. If this is the case, then the account cannot search the domain corpus because the requesting account does not have a domain.

To impersonate a user, config.Subject should be set to a domain account to impersonate, in which case the request will then make a request as if it were the subject user. This is documented [here](https://godoc.org/golang.org/x/oauth2/jwt#Config) for the go library. [Here](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) are the main docs for how to use OAuth with domain-wide delegation.

Ideally we would have a better error message here, but the actual check is done by one of our backends. We're working on improving error messages for future versions of the API.

**Comment by jacksongabbard** [comment]
Oh, wow. Yeah, this is pretty non-obvious from the API documentation. I'll give it a try and report back.

**Comment by jacksongabbard** [comment]
Yup. Confirmed this works as advertised. Thanks for chasing the solution down.
