### ISSUE TITLE
ServiceAccounts.Keys.Create return nil and error 404 just after create

### ISSUE THREAD

**Issue by sebglon** [google/google-api-go-client#234]
A few time ago, when i use service clientIAM.Projects.ServiceAccounts.Keys.Create
it return serviceAccountKey = nil and error = nil...

When i have this error, i create one on google console and have an error.
Is it possible to have an operation object or solve async task?

Because create finish in 200 but if you make get just after we have 404 with the generated key name.
If i wait 10 sec under create and get, i have get 200.

**Comment by jpharaoh-google** [comment]
I have been assisting the user who raised this issue in my role for Google Cloud Platform Support. The issue is that the API call to create a service account key does not return the public key, and the call to get the key, which does include it, does not succeed until some time after the key is created.

One solution I have suggested is to poll the API call to get the key periodically until the public key is returned.

I also note that the public key itself is technically contained in the response to the "create key" call, since it can be extracted from the private key. This is, however, unsigned, whereas the "get key" call eventually returns a certificate, ie a signed copy of the public key.

I don't believe this is an issue in this API client, since it maps directly to the public API. I do believe the API could provide a solution to this rather than polling, and will suggest this as a potential feature.

Since this actually relates to the API, rather than the API client, I believe this issue should be closed. An appropriate place to suggest a change to the API itself would be the Google Cloud Platform IAM idea forum:

https://googlecloudplatform.uservoice.com/forums/580999-cloud-identity-access-management-iam

**Comment by jba** [comment]
> Since this actually relates to the API, rather than the API client, I believe this issue should be closed.

Agreed.

**Comment by arekkas** [comment]
Has this been reported to the GCP IAM Team or has this issue simply been closed without follow up?
