### ISSUE TITLE
Can I get the contents and titles of emails?

### ISSUE THREAD

**Issue by sdwkn** [google/google-api-go-client#258]
I want to get the contents and titles of emails, but can't I do that from the API?

If I want to achieve this, should I access it using imap 4?

type Message.Raw does not seem to have a value.

**Comment by jba** [comment]
Which Go package in this repo are you referring to?

Also, we may not be able to help you because the code in this repo is generated from the discovery document (machine-readable description) of the API. You should probably begin by consulting the API reference first, and only file an issue here if you believe the generated client does not correctly implement the API.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
