### ISSUE TITLE
GCS - Can I create a Resumable Upload session without uploading data?

### ISSUE THREAD

**Issue by EVILoptimist** [google/google-api-go-client#96]
I've seen some great functionality in this project for using Resumable Uploads with Go and GCS. (#17)

I haven't been able to figure out if there's a way that I can create a Resumable Upload session using the credentials, etc. on my App Engine project, and then extract the "Location" header and send to my client to actually complete the file upload.

The process is described in the "Using a signed URL for resumable uploads" section here: https://cloud.google.com/storage/docs/access-control#Signed-URLs

Any help/feedback would be appreciated :)

**Comment by drichardson** [comment]
I was recently looking into this myself. I haven't done a resumable upload/signed URL, but I have got this library to work with my app engine credentials, so read on to solve at list that part of the problem.

Besides the google-api-go-client, there's also:
- the [classic appengine package](https://cloud.google.com/appengine/docs/go/reference)
- a [appengine package for managed VMs](https://github.com/golang/appengine)
- the [cloud package](https://godoc.org/google.golang.org/cloud)

The [cloud package](https://godoc.org/google.golang.org/cloud), in particular, contains a [storage example](https://godoc.org/google.golang.org/cloud/examples/storage/appengine) that is referenced from the [Google Cloud online documentation](https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/getstarted). This example might be useful to you, because it shows you how to get an context.Context (required by google-api-go-client) from an appengine.Context.

Before you get too excited, however, you should note the Context from the managed VM app engine project I mentioned above is a context.Context, not an appengine.Context. So if you adopt this approach you'll have to convert your code per the instructions in the [README](https://github.com/golang/appengine#3-update-code-using-deprecated-removed-or-modified-apis). And, you should also know that it isn't 100% backwards compatible with the classic appengine package, and one of the major things the new package is missing is aetest.

**Comment by EVILoptimist** [comment]
+1

Looks like we're both on the same track. Thanks for the follow up! Very useful.

**Comment by EVILoptimist** [comment]
And, yes. Looks like the missing aetest package is causing problems in my project as well... :S

**Comment by drichardson** [comment]
To follow up again... because I found myself finding my own answer above while Googling about creating http.Clients from app engine for the Google APIs for Go library...

I have a set of appengine helper packages that fill a few of the gaps between Go App Engine, compute engine, and the Google APIs for Go library. Specifically, I added [a function to create an http.Client](https://godoc.org/github.com/drichardson/appengine/googleapiclient) that can be used with the Google APIs for Go library directly from App Engine. 

Note, this code only works with the [this appengine package](https://github.com/golang/appengine). It does not work with [default appengine package](https://cloud.google.com/appengine/docs/go/reference).

**Comment by evanj** [comment]
The API now has a ResumableMedia option in the storage package, but it does not appear to work correctly. When I try to use it, it uploads the first chunk only, resulting in a truncated file. It looks like I may have to assemble my own from the lower-level components available in this package.

**Comment by mcgreevy** [comment]
@evanj can you paste a minimal code snippet to show how you are using ResumableMedia when it results in a truncated file?

**Comment by evanj** [comment]
Never mind! I misunderstood the API. I was assuming I could use it to stream contents of unknown size, but that appears to not be the case: It seems that the size parameter must be passed, and it will truncate the reader you pass in to that size (which does make sense).

So, this issue is still valid: I would also like a way to create a resumable session, send a few chunks, then send a few chunks later. My use case is that I'd like to stream data of unknown size in a way that survives process restarts. I've hacked this up using the API directly and it seems to work as desired. It would be nice to have a friendly "wrapper" for it.

**Comment by jba** [comment]
Neither this storage client nor its successor at cloud.google.com/go/storage supports this ability. We don't have plans to add this feature to these clients.

**Comment by ehmo** [comment]
@jba Any reason for that? This would be very useful and it's supported functionality of the GCS. Why would you not add support to the official library? The alternative to that is to fork it and add ourselves? I find this very peculiar.
